# Site settings
title: Welcome Aboard
default_author: Danni Setiawan
description: "bridging ideas"  # used in site head

# register on google analytics and replace this token
google_analytics: 
# disque comments are broken if you send http:// along with url, this url is same as the one given on disqus
# Deleting the value would remove it from footer.
# disqus_url: shikherverma.com
# disqus_id: shikherverma
# register on feedburner and replace this url. Deleting the value will remove it from footer.
# feedburner_url: https://feedburner.google.com/fb/a/mailverify?uri=programmer-wannabe&amp;loc=en_US

# footer details. Deleting the value would remove it from footer.
github_username:  danninov
facebook_username:
email: me@danni.id
stackoverflow_username:
twitter_username : danninovandri
linkedin_username : 
keybase_username :
copyright_name: Danni Setiawan
rss : false

# used for portfolio on home page
#collections:
#  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: blog/page:num

# gem dependencies
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]
